Progressbar
front-end-by-rimantas/12-grupe-portfolio-potato pull request #42
Opened 2020-01-16 00:51 UTC by varveklis6

2020-01-16 08:19 UTC, Gabrieliusv requested changes

2020-01-16 08:19 UTC, Gabrieliusv commented on css/progress-bars.scss
> +      flex-wrap: wrap;
`flex-wrap: wrap;` nereikia. Be jo geresnis responsive ant 320px ir mažesnių screen.

2020-01-16 08:19 UTC, Gabrieliusv commented on css/progress-bars.scss
> +      flex-wrap: wrap;
` flex-wrap: wrap;` irgi nereikia, nes niekada newrapins.

2020-01-16 08:19 UTC, Gabrieliusv commented on js/functions.js
> +                   //  ar galiu data-animation deti cia? ar i HTML reikiia?
nelabai supratau klausimo :D tau reikia tik atskiros funkcijos kuri užmestų klasę animation, ir ji turėtų būti iškviečiama kai scrollintu.

2020-01-16 08:19 UTC, Gabrieliusv commented on js/actions.js
> +renderBrogressBar( ProgressBar );
`window.addEventListener('scroll', updateOnScroll);`
toki damesti ir sukurti funkcija  updateOnScroll kuri iškviestu visas funkcijas kuriom bus reikalinga pozicija ekrano.

2020-01-16 09:20 UTC, varveklis6 commented on css/progress-bars.scss
> +      flex-wrap: wrap;
taigi ne akmens am=ius, kas 320px screena naudoja :D

2020-01-16 09:25 UTC, varveklis6 commented on js/functions.js
> +                   //  ar galiu data-animation deti cia? ar i HTML reikiia?
jau išsprendžiau štą  bėdutę :D
o mes turim tokią klasę jau, kuri iškviečia kai užscrolini?? ar reik pakurt?

2020-01-16 09:26 UTC, varveklis6 commented on js/actions.js
> +renderBrogressBar( ProgressBar );
gerai, sukursiu :D

2020-01-16 09:27 UTC, Gabrieliusv commented on css/progress-bars.scss
> +      flex-wrap: wrap;
Bet tuomet taisyklė išvis nereikalinga :DD

2020-01-16 09:29 UTC, Gabrieliusv commented on js/functions.js
> +                   //  ar galiu data-animation deti cia? ar i HTML reikiia?
po šituo comment'u damečiau kaip maždaug turėtų būti :D

2020-01-16 10:58 UTC, varveklis6 commented on css/progress-bars.scss
> +      flex-wrap: wrap;
nu ok, ištryniau

2020-01-17 15:33 UTC, Gabrieliusv approved these changes

2020-01-17 15:33 UTC, merged